### ISSUE TITLE
AttributeError while running generate.py

### ISSUE THREAD

**Issue by rodinf** [bamos/cv#25]
Command `make stage` gives:
```
./generate.py cv.yaml
Processing section: about
Processing section: positions
Processing section: education
Processing section: industry
Processing section: honors
Processing section: all_publications
Processing section: repos
Traceback (most recent call last):
  File "./generate.py", line 616, in <module>
    main()
  File "./generate.py", line 611, in main
    process_resume(LATEX_CONTEXT, yaml_data, args.preview)
  File "./generate.py", line 578, in process_resume
    rendered_resume = context.render_resume(yaml_data)
  File "./generate.py", line 476, in render_resume
    add_repo_data(self, section_content)
  File "./generate.py", line 388, in add_repo_data
    item['stars'] = soup.find(
AttributeError: 'NoneType' object has no attribute 'text'
make: *** [Makefile:35: build/cv.tex] Error 1
```
What's goes wrong?

**Comment by bamos** [comment]
Ah oops, it's coming from the code that looks up and saves the number of stars the github repos have. It was a hacky piece of code that scrapes the HTML of repo pages that github seems to have changed since I wrote that. It may work if you comment out the `repos` line in `order` in `cv.yaml` to disable the repos for now, or you can disable that section in `generate.py`

**Comment by bamos** [comment]
Fixed in https://github.com/bamos/cv/commit/0719d557700fd912482fca8be41795165905101d
