### ISSUE TITLE
UnicodeEncodeError:

### ISSUE THREAD

**Issue by jetheurer** [bamos/cv#9]
I was getting this error:

```
Traceback (most recent call last):
  File "generate.py", line 289, in <module>
    main()
  File "generate.py", line 284, in main
    process_resume(LATEX_CONTEXT, yaml_data, args.preview)
  File "generate.py", line 255, in process_resume
    context.write_to_outfile(rendered_resume)
  File "generate.py", line 209, in write_to_outfile
    out.write(output_data)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1387: ordinal not in range(128)
```
is fixed with:

```python
output_data = output_data.encode('utf-8')
```

**Comment by bamos** [comment]
Thanks for the report and fix @jetheurer!

Can you see if it still works for you?
I changed the `open` to binary mode to
fix the following error in Arch Linux:

```
cv(master*)$ m build/cv.md
./generate.py cv.yaml
  + Processing section: interests
  + Processing section: education
  + Processing section: research
  + Processing section: teaching
  + Processing section: publications
  + Processing section: industry
  + Processing section: skills
  + Processing section: honors
Traceback (most recent call last):
  File "./generate.py", line 290, in <module>
    main()
  File "./generate.py", line 285, in main
    process_resume(LATEX_CONTEXT, yaml_data, args.preview)
  File "./generate.py", line 256, in process_resume
    context.write_to_outfile(rendered_resume)
  File "./generate.py", line 210, in write_to_outfile
    out.write(output_data)
TypeError: must be str, not bytes
Makefile:31: recipe for target 'build/cv.md' failed
make: *** [build/cv.md] Error 1
```

**Comment by bamos** [comment]
Also @jetheurer - I think this bug was hidden in my system
because my LOCALE includes UTF-8.
My guess is that your LOCALE doesn't,
and I think I've run into this in another project when
running code on different computers.
Would be nice for Python to tell me about this
incompatibility. :-)

```
~$ echo $LANGUAGE $LC_ALL $LC_CTYPE $LANG
en_US.UTF-8 en_US.UTF-8
```

**Comment by bamos** [comment]
@jetheurer - I'm closing this issue because I think this issue is resolved.
Ping me if something isn't working for you.

**Comment by jetheurer** [comment]
ah sorry Brandon, I havent gotten around to checking it yet.

Liz
